-- Single-use invite codes for the closed-beta tester signup gate. See:
--   docs/superpowers/specs/2026-05-12-admin-tooling-and-invite-gate-design.md
-- Codes are generated by admins via /admin, shared out-of-band, consumed at
-- signup. Single-use is enforced by 'consumed_by' column + row lock in the
-- consume RPC. Expired/revoked codes stay in the table for audit trail.

create table public.invite_codes (
  code text primary key,
  created_by uuid not null references public.profiles(user_id),
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  consumed_by uuid references public.profiles(user_id),
  consumed_at timestamptz,
  note text
);

create index invite_codes_created_at_idx on public.invite_codes (created_at desc);
create index invite_codes_unused_idx on public.invite_codes (created_at desc)
  where consumed_by is null;

alter table public.invite_codes enable row level security;

-- Admins do everything via the table. Non-admins have zero access.
-- Signup flow uses consume_invite_code() RPC under service-role.
create policy invite_codes_admin_all on public.invite_codes
  for all
  using (public.has_role('admin'))
  with check (public.has_role('admin'));

-- Consume RPC: validates + marks used in a single locked transaction.
-- Service-role only, called from app/(auth)/sign-up/actions.ts after
-- auth.signUp() creates the user. Caller is responsible for rolling back
-- the new auth.users row if this raises.
create or replace function public.consume_invite_code(
  p_code text,
  p_user_id uuid
) returns void
language plpgsql security definer
as $$
declare
  v_consumed_by uuid;
  v_expires_at timestamptz;
begin
  -- Row-level lock prevents two concurrent signups racing on same code.
  select consumed_by, expires_at into v_consumed_by, v_expires_at
  from public.invite_codes
  where code = p_code
  for update;

  if not found then
    raise exception 'invalid_invite_code';
  end if;
  if v_consumed_by is not null then
    raise exception 'invite_code_already_used';
  end if;
  if v_expires_at is not null and v_expires_at < now() then
    raise exception 'invite_code_expired';
  end if;

  update public.invite_codes
  set consumed_by = p_user_id,
      consumed_at = now()
  where code = p_code;
end;
$$;

-- Service-role only; never callable by authenticated users directly.
revoke execute on function public.consume_invite_code(text, uuid) from public;
revoke execute on function public.consume_invite_code(text, uuid) from authenticated;
grant execute on function public.consume_invite_code(text, uuid) to service_role;

comment on table public.invite_codes is
  'Single-use signup invite codes. Generated by admins; consumed at signup via consume_invite_code() under service-role.';
comment on function public.consume_invite_code(text, uuid) is
  'Atomically validate + mark consumed. Raises invalid_invite_code / invite_code_already_used / invite_code_expired. Service-role only.';
